# UDP Client

from socket import *
import time

#serverName = 'hostname'
receiver_ip = '192.168.50.179'

receiver_port = 13000

# create UDP socket
sender_udp_socket = socket( AF_INET, SOCK_DGRAM )


sequence_number = 10001
payload = 'M' * 1452 #Payload: 1500−28=1472-5(10001)-4("####")-1(;) = 1462 bytes (maximum payload size). Using 1452 bytes leaves a small buffer for safety.  1 byte (8 bits) = 1 character in ASCII encoding.
termination = "####"

duration_seconds = 30
f = 15 # 15 packets/second
end_time = time.time() + duration_seconds

try:
    while time.time() < end_time:
        # Construct the message
        message = f"{sequence_number};{payload}{termination}".encode()
        #note:
            #The b'' notation we see in the output is not coming from the server; it is generated by the client code when we encode the message.
            #The b'' indicates that the message is a bytes object, which is necessary for network communication. 
        sender_udp_socket.sendto(message, (receiver_ip, receiver_port))
        # print(message)

        sequence_number += 1
        time.sleep(1/f)# 15 packets/second
except KeyboardInterrupt:
    print(" Interrupted")

# close UDP socket
sender_udp_socket.close()
