# TCP Client

from socket import *
import time

#serverName = 'hostname'
receiver_ip = '192.168.50.238'

receiver_port = 12000

# create TCP socket
sender_tcp_socket = socket( AF_INET, SOCK_STREAM )

# Connect to the TCP server
try:
    sender_tcp_socket.connect((receiver_ip, receiver_port))
    print(f"Connected to {receiver_ip}:{receiver_port}")
except Exception as e:
    print(f"Failed to connect: {e}")
    exit(1)

sequence_number = 10001
payload = 'M' * 1452 #Payload: 1500−28=1472-5(10001)-4("####")-1(;) = 1462 bytes (maximum payload size). Using 1452 bytes leaves a small buffer for safety.  1 byte (8 bits) = 1 character in ASCII encoding.
termination = "####"

duration_seconds = 30
end_time = time.time() + duration_seconds

try:
    while time.time() < end_time:
        # Construct the message
        message = f"{sequence_number};{payload}{termination}".encode()
        #note:
            #The b'' notation we see in the output is not coming from the server; it is generated by the client code when we encode the message.
            #The b'' indicates that the message is a bytes object, which is necessary for network communication. 

        # Send the message via TCP
        sender_tcp_socket.sendall(message) 

        # print(f"Sending to {receiver_ip}:{receiver_port} -> {message}")
        # print(message)

        sequence_number += 1
        time.sleep(1.0/25)# 50 packets/second
except KeyboardInterrupt:
    print(" Interrupted")

# close TCP socket
sender_tcp_socket.close()
print("sender: TCP connection closed...")
